-- V10: Seed de temas y preguntas — Policía Nacional (datos de desarrollo)
-- Carga 5 temas con 10 preguntas MCQ cada uno para permitir generación de planes y tests.
-- Solo para entorno de desarrollo. No incluir datos sensibles.

-- ── Temas ────────────────────────────────────────────────────────────────────

INSERT INTO temas (rama_id, nombre, orden, descripcion_corta, preguntas_count) VALUES
    ((SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional'), 'Constitución Española',               1, 'Estructura, principios y artículos fundamentales de la CE de 1978',         10),
    ((SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional'), 'Derechos y Libertades Fundamentales', 2, 'Título I CE: derechos, deberes y libertades de los ciudadanos',             10),
    ((SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional'), 'Organización del Estado',             3, 'Corona, Cortes Generales, Gobierno y poder judicial',                       10),
    ((SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional'), 'Organización Territorial',            4, 'Comunidades Autónomas, municipios y provincias',                            10),
    ((SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional'), 'Policía Nacional: Organización',      5, 'Estructura, cuerpos, escalas y funciones de la Policía Nacional',           10);

UPDATE ramas_oposiciones SET temas_count = 5 WHERE nombre = 'Policía Nacional';

-- ── Preguntas — Tema 1: Constitución Española ────────────────────────────────

INSERT INTO preguntas (tema_id, enunciado, tipo, opciones, respuesta_correcta, explicacion, dificultad) VALUES

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿En qué año fue aprobada la Constitución Española vigente?',
     'MCQ',
     '["1975","1977","1978","1982"]',
     '1978',
     'La Constitución Española fue aprobada por las Cortes el 31 de octubre de 1978 y ratificada en referéndum el 6 de diciembre de ese mismo año.',
     1),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuántos títulos tiene la Constitución Española de 1978 además del Título Preliminar?',
     'MCQ',
     '["8","9","10","11"]',
     '10',
     'La CE consta de un Título Preliminar más 10 títulos numerados (del I al X), siendo el Título I el más extenso al regular los derechos y deberes fundamentales.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'Según el artículo 1.1 de la Constitución, España se constituye en un Estado social y democrático de Derecho que propugna como valores superiores:',
     'MCQ',
     '["La libertad, la justicia, la igualdad y el pluralismo político","La soberanía, la democracia, la libertad y el orden","La unidad, la paz, el progreso y la justicia","La igualdad, la fraternidad, la solidaridad y la paz"]',
     'La libertad, la justicia, la igualdad y el pluralismo político',
     'El artículo 1.1 CE establece: "España se constituye en un Estado social y democrático de Derecho, que propugna como valores superiores de su ordenamiento jurídico la libertad, la justicia, la igualdad y el pluralismo político."',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'La soberanía nacional reside en el pueblo español, del que emanan los poderes del Estado. ¿En qué artículo de la Constitución se recoge este principio?',
     'MCQ',
     '["Artículo 1.2","Artículo 2","Artículo 9.1","Artículo 14"]',
     'Artículo 1.2',
     'El artículo 1.2 CE establece: "La soberanía nacional reside en el pueblo español, del que emanan los poderes del Estado."',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'La reforma de los artículos 1 al 9 de la Constitución Española requiere:',
     'MCQ',
     '["Mayoría absoluta del Congreso","Mayoría de tres quintos de ambas Cámaras","Aprobación por mayoría de dos tercios de cada Cámara, disolución de las Cortes y ratificación en referéndum","Mayoría simple del Congreso y el Senado"]',
     'Aprobación por mayoría de dos tercios de cada Cámara, disolución de las Cortes y ratificación en referéndum',
     'El artículo 168 CE establece el procedimiento agravado de reforma: dos tercios de cada Cámara, disolución, nuevas elecciones, ratificación por las nuevas Cámaras y referéndum obligatorio.',
     4),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuál es la capital del Estado según la Constitución Española?',
     'MCQ',
     '["Barcelona","Sevilla","Madrid","Toledo"]',
     'Madrid',
     'El artículo 5 CE establece: "La capital del Estado es la villa de Madrid."',
     1),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'El castellano es la lengua española oficial del Estado. ¿Qué dice la Constitución sobre las demás lenguas españolas?',
     'MCQ',
     '["No tienen reconocimiento constitucional","Son cooficiales en todo el territorio nacional","También serán oficiales en las respectivas Comunidades Autónomas de acuerdo con sus Estatutos","Son patrimonio cultural protegido pero sin carácter oficial"]',
     'También serán oficiales en las respectivas Comunidades Autónomas de acuerdo con sus Estatutos',
     'El artículo 3.2 CE establece que las demás lenguas españolas serán también oficiales en las respectivas Comunidades Autónomas de acuerdo con sus Estatutos.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué organismo es el intérprete supremo de la Constitución Española?',
     'MCQ',
     '["El Tribunal Supremo","El Tribunal Constitucional","El Consejo de Estado","El Defensor del Pueblo"]',
     'El Tribunal Constitucional',
     'Según el artículo 1 de la Ley Orgánica del Tribunal Constitucional, este órgano es el intérprete supremo de la Constitución, siendo único en su orden y sus resoluciones no tienen más recurso.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué artículo de la Constitución establece el principio de legalidad y la jerarquía normativa?',
     'MCQ',
     '["Artículo 1","Artículo 9.3","Artículo 14","Artículo 24"]',
     'Artículo 9.3',
     'El artículo 9.3 CE garantiza el principio de legalidad, la jerarquía normativa, la publicidad de las normas, la irretroactividad de las disposiciones sancionadoras no favorables, la seguridad jurídica, la responsabilidad y la interdicción de la arbitrariedad de los poderes públicos.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Constitución Española' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'Según la Constitución, ¿quién puede declarar los estados de alarma, excepción y sitio?',
     'MCQ',
     '["El Rey, a propuesta del Presidente del Gobierno","El Congreso de los Diputados","El Gobierno, con autorización del Congreso según el caso","El Senado"]',
     'El Gobierno, con autorización del Congreso según el caso',
     'El artículo 116 CE regula estos estados: el estado de alarma lo declara el Gobierno por decreto; el de excepción requiere autorización previa del Congreso; el de sitio lo declara el Congreso por mayoría absoluta.',
     4);

-- ── Preguntas — Tema 2: Derechos y Libertades Fundamentales ──────────────────

INSERT INTO preguntas (tema_id, enunciado, tipo, opciones, respuesta_correcta, explicacion, dificultad) VALUES

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿En qué título de la Constitución Española se regulan los derechos y deberes fundamentales?',
     'MCQ',
     '["Título Preliminar","Título I","Título II","Título III"]',
     'Título I',
     'El Título I de la CE (artículos 10 a 55) regula los derechos y deberes fundamentales, dividiéndose en varios capítulos según el grado de protección de cada derecho.',
     1),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuántos días como máximo puede durar la detención preventiva sin que se ponga al detenido a disposición de la autoridad judicial?',
     'MCQ',
     '["24 horas","48 horas","72 horas","96 horas"]',
     '72 horas',
     'El artículo 17.2 CE establece que la detención preventiva no podrá durar más del tiempo estrictamente necesario para la realización de las averiguaciones tendentes al esclarecimiento de los hechos, y, en todo caso, en el plazo máximo de setenta y dos horas.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'El derecho a la inviolabilidad del domicilio se recoge en el artículo 18.2 de la CE. ¿En qué supuestos puede entrarse en un domicilio sin el consentimiento del titular?',
     'MCQ',
     '["Con autorización judicial o en caso de flagrante delito","Siempre que lo solicite la Policía","En cualquier caso de urgencia policial","Solo con mandamiento judicial, sin excepciones"]',
     'Con autorización judicial o en caso de flagrante delito',
     'El artículo 18.2 CE establece que el domicilio es inviolable y solo puede entrar y registrarse con consentimiento del titular, en virtud de resolución judicial, o en caso de flagrante delito.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué recurso específico protege los derechos fundamentales reconocidos en los artículos 14 a 29 de la Constitución?',
     'MCQ',
     '["Recurso de amparo","Recurso de inconstitucionalidad","Cuestión de inconstitucionalidad","Recurso contencioso-administrativo"]',
     'Recurso de amparo',
     'El recurso de amparo ante el Tribunal Constitucional (art. 53.2 CE) protege los derechos comprendidos en los artículos 14 a 29, así como la objeción de conciencia del artículo 30.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'El principio de igualdad ante la ley se recoge en el artículo 14 de la CE. ¿Cuál de las siguientes NO es una causa de discriminación expresamente prohibida en ese artículo?',
     'MCQ',
     '["Nacimiento","Raza","Orientación sexual","Religión"]',
     'Orientación sexual',
     'El artículo 14 CE prohíbe la discriminación por nacimiento, raza, sexo, religión, opinión o cualquier otra condición. La orientación sexual no se menciona expresamente, aunque la jurisprudencia la incluye en "cualquier otra condición".',
     4),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿A qué edad se alcanza la mayoría de edad en España según la Constitución?',
     'MCQ',
     '["16 años","17 años","18 años","21 años"]',
     '18 años',
     'El artículo 12 CE establece: "Los españoles son mayores de edad a los dieciocho años."',
     1),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'El "habeas corpus" es un procedimiento constitucional que permite:',
     'MCQ',
     '["Recurrir ante el Tribunal Constitucional cualquier ley","Solicitar la revisión judicial inmediata de una detención ilegal","Interponer una queja ante el Defensor del Pueblo","Exigir responsabilidad penal a un juez"]',
     'Solicitar la revisión judicial inmediata de una detención ilegal',
     'El artículo 17.4 CE prevé la ley de habeas corpus para producir la inmediata puesta a disposición judicial de toda persona detenida ilegalmente.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'Según el artículo 20 de la CE, ¿cuál de los siguientes derechos NO se recoge expresamente?',
     'MCQ',
     '["Libertad de expresión","Derecho a comunicar información veraz","Libertad de prensa sin restricciones","Libertad de cátedra"]',
     'Libertad de prensa sin restricciones',
     'El artículo 20 CE reconoce la libertad de expresión, el derecho a comunicar información veraz, la libertad de cátedra y la producción literaria y artística. Ningún derecho es absolutamente irrestricto.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuál de los siguientes derechos puede ser suspendido individualmente para personas investigadas por bandas armadas o terroristas?',
     'MCQ',
     '["Libertad de expresión","Inviolabilidad del domicilio e intervención de comunicaciones","Derecho de asociación","Derecho de sufragio"]',
     'Inviolabilidad del domicilio e intervención de comunicaciones',
     'El artículo 55.2 CE permite que una ley orgánica determine la suspensión individual de los derechos de los artículos 17.2, 18.2 y 18.3 para personas investigadas en relación con actividades de bandas armadas o terroristas.',
     4),

    ((SELECT id FROM temas WHERE nombre = 'Derechos y Libertades Fundamentales' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'El derecho a la educación se recoge en el artículo 27 de la CE. ¿Cuál es la edad establecida para la enseñanza obligatoria?',
     'MCQ',
     '["La ley fija la edad obligatoria, no la Constitución","Hasta los 14 años","Hasta los 16 años","Hasta los 18 años"]',
     'La ley fija la edad obligatoria, no la Constitución',
     'El artículo 27.4 CE establece que "la enseñanza básica es obligatoria y gratuita" pero no fija una edad concreta; es la Ley Orgánica de Educación la que determina la escolarización obligatoria hasta los 16 años.',
     4);

-- ── Preguntas — Tema 3: Organización del Estado ──────────────────────────────

INSERT INTO preguntas (tema_id, enunciado, tipo, opciones, respuesta_correcta, explicacion, dificultad) VALUES

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuántos senadores componen el Senado según la Constitución (en su composición mínima básica)?',
     'MCQ',
     '["200","208","265","350"]',
     '208',
     'La CE no fija un número exacto de senadores ya que depende de la población. Sin embargo, la composición mínima básica por circunscripción provincial (4 por provincia + Ceuta y Melilla) arroja en torno a 208 senadores provinciales, a los que se suman los designados por las CCAA.',
     4),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuántos diputados tiene el Congreso de los Diputados según la Constitución?',
     'MCQ',
     '["300 como mínimo y 350 como máximo","350","400","Entre 300 y 400"]',
     '300 como mínimo y 350 como máximo',
     'El artículo 68.1 CE establece que el Congreso se compone de un mínimo de 300 y un máximo de 400 Diputados. La Ley Electoral fijó ese número en 350.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Quién nombra al Presidente del Gobierno en España?',
     'MCQ',
     '["El Congreso de los Diputados por mayoría absoluta","El Rey, a propuesta del candidato investido por el Congreso","Las Cortes Generales reunidas en sesión conjunta","El pueblo español mediante elección directa"]',
     'El Rey, a propuesta del candidato investido por el Congreso',
     'El artículo 99 CE establece que el Rey propone un candidato a Presidente del Gobierno tras las consultas con los grupos parlamentarios. Una vez obtenida la confianza del Congreso, el Rey lo nombra.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'La Corona española es hereditaria. Según la Constitución, ¿qué principio rige la sucesión cuando concurren en el mismo grado?',
     'MCQ',
     '["El varón precede a la mujer","El de mayor edad precede al de menor","La mujer precede al varón","Se determina por sorteo entre el Gobierno y las Cortes"]',
     'El varón precede a la mujer',
     'El artículo 57.1 CE establece el orden de sucesión: en el mismo grado, el varón a la mujer; en el mismo sexo, el de menor edad al de mayor; y en el mismo grado y sexo, el de la línea más próxima.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué institución ostenta el control externo de la actividad económico-financiera del sector público?',
     'MCQ',
     '["El Ministerio de Hacienda","El Tribunal de Cuentas","El Consejo de Estado","La Intervención General del Estado"]',
     'El Tribunal de Cuentas',
     'El artículo 136 CE establece que el Tribunal de Cuentas es el supremo órgano fiscalizador de las cuentas y de la gestión económica del Estado y del sector público.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿En qué consiste la moción de censura constructiva en España?',
     'MCQ',
     '["El Congreso puede destituir al Presidente sin proponer alternativa","El Congreso propone simultáneamente un candidato alternativo al Presidente","El Senado puede retirar la confianza al Gobierno","El Rey puede disolver el Gobierno sin intervención parlamentaria"]',
     'El Congreso propone simultáneamente un candidato alternativo al Presidente',
     'El artículo 113 CE exige que la moción de censura incluya un candidato a la Presidencia del Gobierno. Si prospera, el Rey nombra automáticamente al candidato propuesto, lo que garantiza continuidad de gobierno.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuál es el mandato del Defensor del Pueblo?',
     'MCQ',
     '["4 años","5 años","6 años","Indefinido"]',
     '5 años',
     'La Ley Orgánica 3/1981 del Defensor del Pueblo establece un mandato de cinco años, renovable.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'El Consejo General del Poder Judicial está formado por el Presidente del Tribunal Supremo, que lo presidirá, y:',
     'MCQ',
     '["12 vocales","18 vocales","20 vocales","24 vocales"]',
     '20 vocales',
     'El artículo 122.3 CE establece que el CGPJ estará integrado por el Presidente del Tribunal Supremo, que lo presidirá, y por 20 miembros nombrados por el Rey por un período de cinco años.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Con qué mayoría se aprueba la investidura del Presidente del Gobierno en segunda votación?',
     'MCQ',
     '["Mayoría absoluta","Mayoría de dos tercios","Mayoría simple","Mayoría de tres quintos"]',
     'Mayoría simple',
     'El artículo 99.3 CE establece que si en primera votación no se obtiene la mayoría absoluta, se somete a nueva votación 48 horas después y bastará la mayoría simple (más votos a favor que en contra).',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización del Estado' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuál es el plazo máximo para que el Rey sancione y promulgue una ley aprobada por las Cortes?',
     'MCQ',
     '["7 días","15 días","30 días","60 días"]',
     '15 días',
     'El artículo 91 CE establece que el Rey sancionará en el plazo de quince días las leyes aprobadas por las Cortes Generales, y las promulgará y ordenará su inmediata publicación.',
     3);

-- ── Preguntas — Tema 4: Organización Territorial ─────────────────────────────

INSERT INTO preguntas (tema_id, enunciado, tipo, opciones, respuesta_correcta, explicacion, dificultad) VALUES

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuántas Comunidades Autónomas existen en España?',
     'MCQ',
     '["15","17","19","21"]',
     '17',
     'España está organizada en 17 Comunidades Autónomas, además de las ciudades autónomas de Ceuta y Melilla, que tienen un estatuto especial.',
     1),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'El principio de autonomía de las nacionalidades y regiones se recoge en:',
     'MCQ',
     '["Artículo 1 CE","Artículo 2 CE","Artículo 8 CE","Artículo 137 CE"]',
     'Artículo 2 CE',
     'El artículo 2 CE reconoce y garantiza el derecho a la autonomía de las nacionalidades y regiones que la integran y la solidaridad entre todas ellas.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuál es el plazo mínimo de ejercicio de la autonomía que exigía la Constitución por la vía ordinaria (art. 143) para acceder a mayores competencias?',
     'MCQ',
     '["3 años","5 años","8 años","10 años"]',
     '5 años',
     'El artículo 148.2 CE permite que transcurridos cinco años las CCAA de vía lenta puedan ampliar sus competencias mediante reforma de sus Estatutos hasta alcanzar las del artículo 149.',
     4),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué órgano es competente para resolver los conflictos de competencia entre el Estado y las Comunidades Autónomas?',
     'MCQ',
     '["El Tribunal Supremo","El Consejo de Estado","El Tribunal Constitucional","El Senado"]',
     'El Tribunal Constitucional',
     'El Tribunal Constitucional resuelve los conflictos constitucionales de competencia entre el Estado y las CC. AA., según el artículo 161.1.c CE.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué artículo de la Constitución permite al Estado imponer medidas coercitivas a una Comunidad Autónoma que incumpla sus obligaciones?',
     'MCQ',
     '["Artículo 149","Artículo 150","Artículo 155","Artículo 161"]',
     'Artículo 155',
     'El artículo 155 CE (cláusula de coerción federal) permite al Gobierno, con aprobación del Senado por mayoría absoluta, adoptar medidas para obligar a una CA a cumplir sus obligaciones constitucionales.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'Las leyes marco del artículo 150.1 CE permiten:',
     'MCQ',
     '["Al Estado asumir competencias autonómicas temporalmente","Atribuir a las CC.AA. la facultad de dictar normas en materias de competencia estatal","Armonizar la legislación de las CC.AA. cuando sea necesario para el interés general","Delegar funciones del Estado en los municipios"]',
     'Atribuir a las CC.AA. la facultad de dictar normas en materias de competencia estatal',
     'El artículo 150.1 CE habilita al Estado a dictar leyes marco que atribuyan a las CC. AA. la facultad de dictar normas legislativas en materias de competencia estatal, dentro de los principios y directrices fijados por el Estado.',
     4),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'Los municipios son la entidad local básica de la organización territorial del Estado. ¿Qué órgano es el de gobierno y administración del municipio?',
     'MCQ',
     '["La Diputación Provincial","El Ayuntamiento","La Mancomunidad","La Junta de Gobierno Local"]',
     'El Ayuntamiento',
     'El artículo 140 CE garantiza la autonomía de los municipios, que gozarán de personalidad jurídica plena, y el artículo 19 de la Ley de Bases de Régimen Local establece que el Ayuntamiento es el órgano de gobierno y administración municipal.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuáles son las competencias exclusivas del Estado según el artículo 149.1 CE?',
     'MCQ',
     '["Educación y sanidad","Relaciones internacionales, defensa, administración de justicia y legislación mercantil, entre otras","Urbanismo, vivienda y servicios sociales","Agricultura y ganadería"]',
     'Relaciones internacionales, defensa, administración de justicia y legislación mercantil, entre otras',
     'El artículo 149.1 CE enumera las competencias exclusivas del Estado: relaciones internacionales, defensa, administración de justicia, legislación mercantil, penal y penitenciaria, entre otras materias de ámbito nacional.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'El Senado es definido por la Constitución como:',
     'MCQ',
     '["La Cámara de representación popular","La Cámara de representación territorial","La Cámara de revisión legislativa","El órgano de control del Gobierno"]',
     'La Cámara de representación territorial',
     'El artículo 69.1 CE establece: "El Senado es la Cámara de representación territorial."',
     1),

    ((SELECT id FROM temas WHERE nombre = 'Organización Territorial' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cómo se denomina la norma institucional básica de cada Comunidad Autónoma?',
     'MCQ',
     '["Ley Orgánica","Estatuto de Autonomía","Ley Marco","Carta Magna autonómica"]',
     'Estatuto de Autonomía',
     'El artículo 147.1 CE establece que los Estatutos de Autonomía son la norma institucional básica de cada Comunidad Autónoma, reconocidos y amparados por el Estado como parte integrante de su ordenamiento jurídico.',
     1);

-- ── Preguntas — Tema 5: Policía Nacional: Organización ───────────────────────

INSERT INTO preguntas (tema_id, enunciado, tipo, opciones, respuesta_correcta, explicacion, dificultad) VALUES

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿De qué Ministerio depende la Policía Nacional?',
     'MCQ',
     '["Ministerio de Defensa","Ministerio del Interior","Ministerio de Justicia","Presidencia del Gobierno"]',
     'Ministerio del Interior',
     'La Policía Nacional es un Instituto Armado de naturaleza civil, dependiente del Ministerio del Interior, con estructura jerarquizada.',
     1),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué ley regula las Fuerzas y Cuerpos de Seguridad del Estado?',
     'MCQ',
     '["Ley Orgánica 1/1979","Ley Orgánica 2/1986","Ley Orgánica 4/2010","Ley 17/2015"]',
     'Ley Orgánica 2/1986',
     'La Ley Orgánica 2/1986, de 13 de marzo, de Fuerzas y Cuerpos de Seguridad regula la Policía Nacional, la Guardia Civil y los cuerpos de policía de las CCAA y entidades locales.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuál es la escala de menor categoría de la Policía Nacional?',
     'MCQ',
     '["Escala Ejecutiva","Escala de Subinspección","Escala Básica","Escala Técnica"]',
     'Escala Básica',
     'La estructura de la Policía Nacional contempla las escalas Técnica, Ejecutiva, de Subinspección y Básica. La Escala Básica, en la que se integra el cuerpo de Policía, es la de menor categoría.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué función NO corresponde a la Policía Nacional según la LO 2/1986?',
     'MCQ',
     '["Expedir el Documento Nacional de Identidad","Controlar las fronteras terrestres en toda España","Velar por el cumplimiento de las leyes","Investigar los delitos y perseguir a los delincuentes"]',
     'Controlar las fronteras terrestres en toda España',
     'El control de las fronteras terrestres (principalmente los pasos fronterizos con Francia y Portugal) está compartido con la Guardia Civil. La Policía Nacional ejerce el control en los puertos, aeropuertos y fronteras que se le asignen.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué órgano dirige operativamente la Policía Nacional a nivel nacional?',
     'MCQ',
     '["La Secretaría de Estado de Seguridad","La Dirección General de la Policía","El Ministerio del Interior directamente","La Delegación del Gobierno"]',
     'La Dirección General de la Policía',
     'La Dirección General de la Policía es el órgano superior del Cuerpo Nacional de Policía, con rango de Secretaría de Estado, bajo la dependencia del Ministro del Interior a través de la Secretaría de Estado de Seguridad.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuál es la misión fundamental de la Policía Nacional según la Constitución?',
     'MCQ',
     '["Defender la integridad territorial","Proteger el libre ejercicio de los derechos y libertades y garantizar la seguridad ciudadana","Controlar los servicios de inteligencia","Ejecutar las sentencias judiciales"]',
     'Proteger el libre ejercicio de los derechos y libertades y garantizar la seguridad ciudadana',
     'El artículo 104.1 CE establece que las Fuerzas y Cuerpos de Seguridad, bajo la dependencia del Gobierno, tendrán como misión proteger el libre ejercicio de los derechos y libertades y garantizar la seguridad ciudadana.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     'La Unidad de Intervención Policial (UIP) es especializada en:',
     'MCQ',
     '["Investigación del crimen organizado","Mantenimiento del orden público","Protección de autoridades","Delitos informáticos"]',
     'Mantenimiento del orden público',
     'Las UIPs son unidades especializadas de la Policía Nacional en el mantenimiento del orden público, el control de masas y situaciones de riesgo en eventos o concentraciones.',
     2),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué principio ético fundamental establece la LO 2/1986 para los miembros de las Fuerzas y Cuerpos de Seguridad?',
     'MCQ',
     '["Principio de eficacia sobre todo lo demás","Principio de adecuación al ordenamiento jurídico y respeto a los derechos fundamentales","Principio de obediencia absoluta a sus superiores","Principio de actuación discrecional en situaciones de riesgo"]',
     'Principio de adecuación al ordenamiento jurídico y respeto a los derechos fundamentales',
     'La LO 2/1986 establece en sus principios básicos de actuación que los miembros de las FFCCSS deben actuar con absoluto respeto a la Constitución y al ordenamiento jurídico, y proteger los derechos fundamentales.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Qué unidad de la Policía Nacional se encarga de la lucha contra el terrorismo?',
     'MCQ',
     '["Brigada Provincial de Seguridad Ciudadana","Comisaría General de Información","Brigada de Policía Judicial","Unidad Central de Protección"]',
     'Comisaría General de Información',
     'La Comisaría General de Información es la unidad de la Policía Nacional encargada de la lucha antiterrorista, la inteligencia policial y el análisis de amenazas.',
     3),

    ((SELECT id FROM temas WHERE nombre = 'Policía Nacional: Organización' AND rama_id = (SELECT id FROM ramas_oposiciones WHERE nombre = 'Policía Nacional')),
     '¿Cuál es el rango más alto dentro de la Escala Superior del Cuerpo Nacional de Policía?',
     'MCQ',
     '["Inspector Jefe","Comisario Principal","Comisario General","Inspector"]',
     'Comisario General',
     'En la jerarquía del Cuerpo Nacional de Policía, dentro de la Escala Superior (Técnica), el rango más alto es el de Comisario General, por encima de Comisario Principal y Comisario.',
     3);
