-- V20: Seed de temas y preguntas para ramas restantes (datos de desarrollo)
-- Objetivo: dejar todas las ramas base con 5 temas y 10 preguntas MCQ por tema.

-- 1) Temas base para ramas sin contenido inicial
INSERT INTO temas (rama_id, nombre, orden, descripcion_corta, preguntas_count)
SELECT r.id, t.nombre, t.orden, t.descripcion, 10
FROM ramas_oposiciones r
CROSS JOIN (
    VALUES
        ('Constitucion Espanola', 1, 'Principios constitucionales y estructura basica del Estado'),
        ('Derechos y Libertades Fundamentales', 2, 'Derechos, garantias y proteccion constitucional'),
        ('Organizacion del Estado y Administracion', 3, 'Instituciones del Estado y funcionamiento administrativo'),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', 4, 'Marco basico de igualdad, privacidad y seguridad laboral')
) AS t(nombre, orden, descripcion)
WHERE r.nombre IN (
    'Guardia Civil',
    'Cuerpo de Ayudantes de II.PP. (Prisiones)',
    'Fuerzas Armadas',
    'Técnico Auxiliar Sanitario'
);

INSERT INTO temas (rama_id, nombre, orden, descripcion_corta, preguntas_count)
SELECT r.id, t.nombre, 5, t.descripcion, 10
FROM ramas_oposiciones r
JOIN (
    VALUES
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'Estructura, funciones y marco funcional de la Guardia Civil'),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'Normativa y funcionamiento basico del entorno penitenciario'),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'Organizacion militar, mision constitucional y marco de defensa'),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'Apoyo asistencial, seguridad del paciente y trabajo clinico basico')
) AS t(rama_nombre, nombre, descripcion)
ON r.nombre = t.rama_nombre;

UPDATE ramas_oposiciones
SET temas_count = 5
WHERE nombre IN (
    'Guardia Civil',
    'Cuerpo de Ayudantes de II.PP. (Prisiones)',
    'Fuerzas Armadas',
    'Técnico Auxiliar Sanitario'
);

-- 2) Preguntas comunes (temas 1 a 4) para todas las ramas restantes
WITH preguntas_base (tema_nombre, enunciado, opciones, respuesta_correcta, explicacion, dificultad) AS (
    VALUES
        -- Tema 1: Constitucion Espanola
        ('Constitucion Espanola', '¿En que ano fue aprobada la Constitucion Espanola vigente?', '["1975","1977","1978","1982"]', '1978', 'La Constitucion fue aprobada en 1978 y ratificada en referendum el 6 de diciembre.', 1),
        ('Constitucion Espanola', 'Segun el articulo 1.1 CE, Espana se constituye en un Estado social y democratico de Derecho que propugna:', '["La libertad, la justicia, la igualdad y el pluralismo politico","La unidad, la seguridad y la eficacia","La tradicion, la autoridad y la soberania","La autonomia, la fraternidad y la paz"]', 'La libertad, la justicia, la igualdad y el pluralismo politico', 'El articulo 1.1 CE enumera expresamente esos cuatro valores superiores.', 2),
        ('Constitucion Espanola', '¿En que articulo se afirma que la soberania nacional reside en el pueblo espanol?', '["Articulo 1.2","Articulo 2","Articulo 9.1","Articulo 14"]', 'Articulo 1.2', 'El articulo 1.2 CE establece la titularidad popular de la soberania nacional.', 1),
        ('Constitucion Espanola', '¿Que articulo fija que la capital del Estado es Madrid?', '["Articulo 3","Articulo 4","Articulo 5","Articulo 8"]', 'Articulo 5', 'La CE indica en su articulo 5 que la capital del Estado es la villa de Madrid.', 1),
        ('Constitucion Espanola', 'El castellano es lengua oficial del Estado. Las demas lenguas espanolas:', '["No tienen reconocimiento constitucional","Son oficiales en todo el Estado","Tambien seran oficiales en sus CCAA segun sus Estatutos","Solo pueden usarse en el ambito privado"]', 'Tambien seran oficiales en sus CCAA segun sus Estatutos', 'El articulo 3.2 CE reconoce la cooficialidad en las CCAA conforme a sus Estatutos.', 2),
        ('Constitucion Espanola', '¿Que procedimiento se aplica para reformar el Titulo Preliminar de la CE?', '["Procedimiento ordinario del art. 167","Procedimiento agravado del art. 168","Decreto-ley del Gobierno","Ley organica sin referendum"]', 'Procedimiento agravado del art. 168', 'La reforma de partes nucleares de la CE exige el procedimiento reforzado del articulo 168.', 4),
        ('Constitucion Espanola', '¿Que articulo garantiza el principio de legalidad y la jerarquia normativa?', '["Articulo 1","Articulo 9.3","Articulo 14","Articulo 24"]', 'Articulo 9.3', 'El articulo 9.3 CE incluye legalidad, jerarquia normativa y seguridad juridica, entre otros principios.', 2),
        ('Constitucion Espanola', '¿Como se define el Senado en la Constitucion?', '["Camara de representacion territorial","Camara de gobierno","Camara judicial","Camara autonoma ejecutiva"]', 'Camara de representacion territorial', 'El articulo 69.1 CE define el Senado como la Camara de representacion territorial.', 1),
        ('Constitucion Espanola', 'La forma politica del Estado espanol es:', '["Monarquia absoluta","Republica parlamentaria","Monarquia parlamentaria","Estado confederal"]', 'Monarquia parlamentaria', 'El articulo 1.3 CE dispone que la forma politica del Estado espanol es la Monarquia parlamentaria.', 1),
        ('Constitucion Espanola', '¿Que mision atribuye el articulo 104 CE a las Fuerzas y Cuerpos de Seguridad?', '["Gestionar la politica exterior","Proteger derechos y libertades y garantizar la seguridad ciudadana","Dirigir la administracion de justicia","Controlar la actividad legislativa"]', 'Proteger derechos y libertades y garantizar la seguridad ciudadana', 'El articulo 104.1 CE establece esa mision general de las Fuerzas y Cuerpos de Seguridad.', 2),

        -- Tema 2: Derechos y Libertades Fundamentales
        ('Derechos y Libertades Fundamentales', '¿En que Titulo de la CE se regulan los derechos y deberes fundamentales?', '["Titulo Preliminar","Titulo I","Titulo II","Titulo III"]', 'Titulo I', 'El Titulo I (articulos 10 a 55) regula derechos y deberes fundamentales.', 1),
        ('Derechos y Libertades Fundamentales', '¿Cual es el plazo maximo ordinario de detencion preventiva sin pasar a disposicion judicial?', '["24 horas","48 horas","72 horas","96 horas"]', '72 horas', 'El articulo 17.2 CE fija un maximo de 72 horas.', 2),
        ('Derechos y Libertades Fundamentales', 'La entrada en domicilio sin consentimiento del titular requiere, con caracter general:', '["Resolucion judicial o flagrante delito","Simple autorizacion policial","Permiso de la administracion local","Solicitud verbal de un agente"]', 'Resolucion judicial o flagrante delito', 'El articulo 18.2 CE protege la inviolabilidad domiciliaria y solo admite supuestos tasados.', 3),
        ('Derechos y Libertades Fundamentales', '¿Que recurso protege ante el Tribunal Constitucional derechos de los articulos 14 a 29 CE?', '["Recurso de amparo","Recurso de revision","Cuestion prejudicial","Incidente de nulidad constitucional"]', 'Recurso de amparo', 'El articulo 53.2 CE preve el amparo constitucional para esos derechos.', 2),
        ('Derechos y Libertades Fundamentales', '¿Que articulo reconoce la igualdad ante la ley y la no discriminacion?', '["Articulo 9","Articulo 10","Articulo 14","Articulo 20"]', 'Articulo 14', 'El articulo 14 CE recoge el derecho a la igualdad y la prohibicion de discriminacion.', 1),
        ('Derechos y Libertades Fundamentales', '¿A que edad se alcanza la mayoria de edad en Espana segun la CE?', '["16 anos","17 anos","18 anos","21 anos"]', '18 anos', 'El articulo 12 CE fija la mayoria de edad en los 18 anos.', 1),
        ('Derechos y Libertades Fundamentales', 'El procedimiento de habeas corpus sirve para:', '["Anular cualquier ley","Controlar judicialmente una detencion ilegal","Recurrir sentencias civiles","Exigir indemnizacion automatica"]', 'Controlar judicialmente una detencion ilegal', 'El habeas corpus garantiza la inmediata puesta a disposicion judicial de detenciones ilegales.', 2),
        ('Derechos y Libertades Fundamentales', 'La libertad ideologica, religiosa y de culto se reconoce en:', '["Articulo 15","Articulo 16","Articulo 18","Articulo 23"]', 'Articulo 16', 'El articulo 16 CE protege estas libertades en sus apartados principales.', 2),
        ('Derechos y Libertades Fundamentales', 'El derecho a comunicar informacion se condiciona constitucionalmente a que sea:', '["Completa","Inmediata","Veraz","Anónima"]', 'Veraz', 'El articulo 20.1.d CE menciona expresamente el derecho a comunicar informacion veraz.', 3),
        ('Derechos y Libertades Fundamentales', 'La tutela judicial efectiva se reconoce en el articulo:', '["Articulo 22","Articulo 23","Articulo 24","Articulo 25"]', 'Articulo 24', 'El articulo 24 CE garantiza tutela judicial efectiva y derecho de defensa.', 2),

        -- Tema 3: Organizacion del Estado y Administracion
        ('Organizacion del Estado y Administracion', '¿Cuantos diputados puede tener el Congreso segun la CE?', '["200 a 300","300 a 400","300 a 350","350 fijos"]', '300 a 400', 'El articulo 68.1 CE establece minimo 300 y maximo 400 diputados.', 2),
        ('Organizacion del Estado y Administracion', 'El Rey sanciona y promulga las leyes en un plazo de:', '["7 dias","15 dias","30 dias","60 dias"]', '15 dias', 'El articulo 91 CE fija quince dias para sancion y promulgacion.', 2),
        ('Organizacion del Estado y Administracion', 'La mocion de censura en Espana tiene caracter:', '["Simple","Constructivo","Consultivo","Automatico"]', 'Constructivo', 'La mocion de censura del articulo 113 CE exige candidato alternativo.', 2),
        ('Organizacion del Estado y Administracion', '¿Que organo fiscaliza externamente las cuentas del sector publico?', '["Intervencion General","Tribunal Supremo","Tribunal de Cuentas","Consejo de Estado"]', 'Tribunal de Cuentas', 'El Tribunal de Cuentas es el supremo organo fiscalizador segun el articulo 136 CE.', 2),
        ('Organizacion del Estado y Administracion', 'La potestad reglamentaria corresponde al Gobierno segun el articulo:', '["97 CE","98 CE","103 CE","106 CE"]', '97 CE', 'El articulo 97 CE atribuye al Gobierno la direccion de la politica y la potestad reglamentaria.', 2),
        ('Organizacion del Estado y Administracion', '¿Que principio rige con caracter general la actuacion de la Administracion publica segun el art. 103 CE?', '["Discrecionalidad plena","Servicio objetivo a los intereses generales","Autonomia absoluta frente a la ley","Reserva corporativa"]', 'Servicio objetivo a los intereses generales', 'El articulo 103 CE fija el servicio objetivo a los intereses generales con sometimiento pleno a la ley y al Derecho.', 2),
        ('Organizacion del Estado y Administracion', 'El Presidente del Gobierno es nombrado por:', '["El Congreso directamente","El Rey tras la investidura","El Senado","El Tribunal Constitucional"]', 'El Rey tras la investidura', 'El articulo 99 CE regula propuesta, investidura en el Congreso y nombramiento real.', 2),
        ('Organizacion del Estado y Administracion', '¿Que Camara puede exigir responsabilidad politica al Gobierno mediante mocion de censura?', '["Senado","Congreso de los Diputados","Ambas en sesion conjunta","Ninguna"]', 'Congreso de los Diputados', 'La mocion de censura corresponde al Congreso conforme al articulo 113 CE.', 2),
        ('Organizacion del Estado y Administracion', '¿Que norma establece las bases del regimen juridico del sector publico y administraciones?', '["Ley 39/2015","Ley 40/2015","Ley 9/2017","Ley 19/2013"]', 'Ley 40/2015', 'La Ley 40/2015 regula el regimen juridico del sector publico.', 2),
        ('Organizacion del Estado y Administracion', '¿Que norma regula con caracter general el procedimiento administrativo comun?', '["Ley 30/1992","Ley 39/2015","Ley 29/1998","Ley 7/1985"]', 'Ley 39/2015', 'La Ley 39/2015 regula el procedimiento administrativo comun de las administraciones publicas.', 2),

        -- Tema 4: Igualdad, Proteccion de Datos y Prevencion de Riesgos
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', '¿Que ley organica regula la igualdad efectiva de mujeres y hombres en Espana?', '["LO 1/2004","LO 3/2007","LO 4/2015","LO 5/2010"]', 'LO 3/2007', 'La Ley Organica 3/2007 es la referencia estatal en igualdad efectiva.', 1),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', 'El principio de minimizacion de datos del RGPD implica:', '["Recoger todos los datos posibles","Tratar solo datos adecuados, pertinentes y limitados","Conservar datos indefinidamente","Publicar datos anonimos sin control"]', 'Tratar solo datos adecuados, pertinentes y limitados', 'El articulo 5.1.c del RGPD exige minimizar los datos al fin perseguido.', 2),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', '¿Que norma adapta en Espana el marco europeo de proteccion de datos?', '["Ley 19/2013","LOPDGDD 3/2018","Ley 39/2015","LO 2/1986"]', 'LOPDGDD 3/2018', 'La LO 3/2018 complementa el RGPD en el ordenamiento espanol.', 2),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', '¿Cual es la finalidad principal de la Ley 31/1995 de Prevencion de Riesgos Laborales?', '["Regular contratos laborales","Promover seguridad y salud de las personas trabajadoras","Determinar salarios minimos","Aprobar convenios colectivos"]', 'Promover seguridad y salud de las personas trabajadoras', 'La Ley 31/1995 se orienta a prevenir danos derivados del trabajo.', 1),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', 'El derecho de acceso a datos personales permite a la persona interesada:', '["Eliminar automaticamente todo dato","Saber si se tratan sus datos y obtener copia","Modificar resoluciones administrativas","Acceder a expedientes de terceros"]', 'Saber si se tratan sus datos y obtener copia', 'El RGPD reconoce el derecho a obtener confirmacion del tratamiento y copia de los datos.', 2),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', 'En prevencion de riesgos, un EPI es:', '["Equipo de Proteccion Individual","Estrategia de Planificacion Interna","Evaluacion Preventiva Integrada","Elemento de Proteccion Institucional"]', 'Equipo de Proteccion Individual', 'EPI significa Equipo de Proteccion Individual para reducir exposicion a riesgos.', 1),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', 'El acoso por razon de sexo en el entorno laboral debe abordarse mediante:', '["Ignorar si no hay denuncia penal","Protocolos internos y medidas preventivas","Solo traslado de la victima","Exclusivamente mediacion informal"]', 'Protocolos internos y medidas preventivas', 'La normativa de igualdad exige medidas de prevencion y actuacion frente al acoso.', 2),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', '¿Que autoridad es referente en Espana en materia de proteccion de datos a nivel estatal?', '["Consejo de Estado","Agencia Espanola de Proteccion de Datos","Defensor del Pueblo","Inspeccion de Trabajo"]', 'Agencia Espanola de Proteccion de Datos', 'La AEPD supervisa y tutela el cumplimiento de la normativa de proteccion de datos.', 1),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', 'La evaluacion de riesgos laborales debe realizarse:', '["Solo al inicio de la actividad","Unicamente tras accidente grave","De forma inicial y cuando cambien condiciones de trabajo","Solo a peticion del personal"]', 'De forma inicial y cuando cambien condiciones de trabajo', 'La gestion preventiva exige evaluacion inicial y actualizaciones ante cambios relevantes.', 2),
        ('Igualdad, Proteccion de Datos y Prevencion de Riesgos', 'El principio de integridad y confidencialidad de datos exige:', '["Difundir datos para contrastarlos","Aplicar medidas de seguridad adecuadas","Conservar datos sin cifrado","Compartir datos por defecto entre organismos"]', 'Aplicar medidas de seguridad adecuadas', 'El RGPD impone proteger datos frente a accesos no autorizados y perdidas.', 2)
)
INSERT INTO preguntas (tema_id, enunciado, tipo, opciones, respuesta_correcta, explicacion, dificultad)
SELECT t.id, pb.enunciado, 'MCQ', pb.opciones::jsonb, pb.respuesta_correcta, pb.explicacion, pb.dificultad
FROM preguntas_base pb
JOIN temas t ON t.nombre = pb.tema_nombre
JOIN ramas_oposiciones r ON r.id = t.rama_id
WHERE r.nombre IN (
    'Guardia Civil',
    'Cuerpo de Ayudantes de II.PP. (Prisiones)',
    'Fuerzas Armadas',
    'Técnico Auxiliar Sanitario'
);

-- 3) Preguntas especificas por rama (tema 5)
WITH preguntas_especificas (rama_nombre, tema_nombre, enunciado, opciones, respuesta_correcta, explicacion, dificultad) AS (
    VALUES
        -- Guardia Civil
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'La Guardia Civil es un instituto armado de naturaleza:', '["Civil","Militar","Mixta autonoma","Judicial"]', 'Militar', 'La normativa de Fuerzas y Cuerpos de Seguridad define la Guardia Civil como instituto armado de naturaleza militar.', 2),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', '¿Que ley organica regula con caracter basico las Fuerzas y Cuerpos de Seguridad?', '["LO 4/2015","LO 2/1986","LO 1/1992","LO 6/1985"]', 'LO 2/1986', 'La Ley Organica 2/1986 es el marco basico de las Fuerzas y Cuerpos de Seguridad.', 1),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'En seguridad ciudadana y orden publico, la Guardia Civil depende principalmente de:', '["Ministerio del Interior","Ministerio de Defensa","Ministerio de Justicia","Presidencia del Gobierno"]', 'Ministerio del Interior', 'Para funciones policiales ordinarias, su dependencia funcional principal es Interior.', 2),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'El Servicio de Proteccion de la Naturaleza (SEPRONA) pertenece a:', '["Policia Nacional","Guardia Civil","Agentes forestales autonomicos","Proteccion Civil"]', 'Guardia Civil', 'SEPRONA es una unidad especializada de la Guardia Civil.', 1),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'Con caracter general, la vigilancia del trafico en vias interurbanas corresponde a:', '["Guardia Civil de Trafico","Policia Local","Jefaturas Provinciales de Trafico","Policia Nacional"]', 'Guardia Civil de Trafico', 'La Agrupacion de Trafico de la Guardia Civil asume esta funcion en vias interurbanas, salvo supuestos transferidos.', 2),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', '¿Que principio debe regir el uso de la fuerza por los miembros de la Guardia Civil?', '["Oportunidad, congruencia y proporcionalidad","Publicidad y transparencia","Rapidez y contundencia","Jerarquia y unilateralidad"]', 'Oportunidad, congruencia y proporcionalidad', 'Los principios basicos de actuacion de las Fuerzas y Cuerpos de Seguridad exigen uso proporcionado de la fuerza.', 3),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'La colaboracion con otras policias en investigaciones se basa en el principio de:', '["Exclusividad competencial","Cooperacion y coordinacion","Reserva de informacion absoluta","Intervencion minima judicial"]', 'Cooperacion y coordinacion', 'El sistema de seguridad publica requiere coordinacion entre cuerpos policiales.', 2),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'La Guardia Civil participa en el resguardo fiscal del Estado y control fronterizo segun:', '["Funciones historicas y normativa vigente","Convenios municipales","Normas internas no publicadas","Mandatos judiciales puntuales exclusivamente"]', 'Funciones historicas y normativa vigente', 'La normativa funcional atribuye tradicionalmente estas competencias a la Guardia Civil en su ambito.', 2),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'La mision general de la Guardia Civil, como fuerza de seguridad, se conecta con:', '["Articulo 104 CE","Articulo 66 CE","Articulo 117 CE","Articulo 148 CE"]', 'Articulo 104 CE', 'La mision de proteger derechos y seguridad ciudadana se integra en el marco del articulo 104 CE.', 2),
        ('Guardia Civil', 'Guardia Civil: Organizacion y Competencias', 'La organizacion territorial de la Guardia Civil se articula mediante:', '["Zonas, Comandancias y Puestos, entre otras unidades","Unicamente delegaciones provinciales civiles","Distritos judiciales exclusivamente","Agrupaciones universitarias"]', 'Zonas, Comandancias y Puestos, entre otras unidades', 'La estructura operativa combina distintos niveles territoriales y especialidades.', 2),

        -- Prisiones
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'La Ley Organica General Penitenciaria es la:', '["LO 2/1986","LO 1/1979","LO 3/2018","LO 5/2000"]', 'LO 1/1979', 'La LO 1/1979 constituye el marco organico basico del sistema penitenciario espanol.', 1),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'El Reglamento Penitenciario vigente se aprobo por:', '["Real Decreto 190/1996","Real Decreto 1720/2007","Ley 39/2015","Ley 40/2015"]', 'Real Decreto 190/1996', 'El Reglamento Penitenciario esta aprobado por el RD 190/1996.', 2),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'La finalidad constitucional de las penas privativas de libertad (art. 25.2 CE) es:', '["Castigo ejemplar","Reeducacion y reinsercion social","Aislamiento permanente","Retencion preventiva indefinida"]', 'Reeducacion y reinsercion social', 'El articulo 25.2 CE orienta las penas a la reeducacion y reinsercion social.', 2),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', '¿Que figura judicial controla la ejecucion penitenciaria y tutela derechos del interno?', '["Juez de Primera Instancia","Juez de Vigilancia Penitenciaria","Fiscal jefe provincial","Magistrado del Tribunal Supremo"]', 'Juez de Vigilancia Penitenciaria', 'El Juez de Vigilancia Penitenciaria ejerce control jurisdiccional especifico en materia penitenciaria.', 2),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'La clasificacion penitenciaria ordinaria se organiza en:', '["Dos grados","Tres grados","Cuatro grados","Cinco grados"]', 'Tres grados', 'El sistema ordinario distingue primer, segundo y tercer grado.', 2),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'El regimen ordinario se asocia, de forma general, al:', '["Primer grado","Segundo grado","Tercer grado","Regimen abierto completo"]', 'Segundo grado', 'Con caracter general, el segundo grado corresponde al regimen ordinario.', 2),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'El tratamiento penitenciario busca principalmente:', '["Incrementar sanciones","Preparar la reinsercion social","Aumentar el aislamiento","Reducir la intervencion profesional"]', 'Preparar la reinsercion social', 'El tratamiento esta orientado a la reinsercion y evolucion personal del interno.', 2),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'El personal del Cuerpo de Ayudantes de II.PP. desarrolla, entre otras, funciones de:', '["Vigilancia, observacion y apoyo al orden interior","Direccion medica hospitalaria","Representacion judicial del interno","Aprobacion de sentencias"]', 'Vigilancia, observacion y apoyo al orden interior', 'El Cuerpo de Ayudantes ejerce funciones nucleares de vigilancia y funcionamiento diario del centro.', 2),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'El principio de legalidad en el ambito penitenciario implica:', '["Actuar solo por instrucciones verbales","Someter toda actuacion a norma y control","Aplicar sanciones sin expediente","Evitar registro documental"]', 'Someter toda actuacion a norma y control', 'La actuacion penitenciaria debe basarse en la ley, reglamento y garantias procedimentales.', 2),
        ('Cuerpo de Ayudantes de II.PP. (Prisiones)', 'Instituciones Penitenciarias: Regimen y Funcion', 'La actividad penitenciaria debe compatibilizar seguridad con:', '["Arbitrariedad disciplinaria","Respeto a la dignidad y derechos fundamentales","Ausencia total de control","Externalizacion judicial completa"]', 'Respeto a la dignidad y derechos fundamentales', 'La ejecucion penitenciaria combina seguridad institucional con garantia de derechos.', 2),

        -- Fuerzas Armadas
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'Segun el articulo 8 CE, las Fuerzas Armadas tienen como mision garantizar:', '["La recaudacion tributaria","La soberania e independencia de Espana, su integridad territorial y el ordenamiento constitucional","La aprobacion de leyes organicas","La direccion judicial del Estado"]', 'La soberania e independencia de Espana, su integridad territorial y el ordenamiento constitucional', 'El articulo 8 CE define esa mision constitucional de las Fuerzas Armadas.', 2),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'La defensa nacional se regula de forma organica, entre otras normas, por:', '["LO 5/2005 de la Defensa Nacional","LO 3/2018","Ley 39/2015","LO 2/1986"]', 'LO 5/2005 de la Defensa Nacional', 'La LO 5/2005 constituye la norma organica de referencia en defensa nacional.', 2),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'Las Fuerzas Armadas espanolas se estructuran en:', '["Ejercito de Tierra, Armada y Ejercito del Aire y del Espacio","Ejercito de Tierra y Marina Civil","Armada y Guardia Civil","Solo Ejercito de Tierra"]', 'Ejercito de Tierra, Armada y Ejercito del Aire y del Espacio', 'La estructura basica integra los tres ejercitos.', 1),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'El mando supremo de las Fuerzas Armadas corresponde a:', '["Presidente del Gobierno","Rey","Ministro de Defensa","JEMAD"]', 'Rey', 'La Constitucion atribuye al Rey el mando supremo de las Fuerzas Armadas.', 1),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'La Ley de la Carrera Militar de referencia es la:', '["Ley 39/2007","Ley 7/2007","Ley 8/2014","Ley 31/1995"]', 'Ley 39/2007', 'La Ley 39/2007 regula aspectos esenciales de la carrera militar.', 2),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'El regimen disciplinario de las Fuerzas Armadas se regula por:', '["LO 8/2014","LO 1/1979","Ley 40/2015","LO 4/2015"]', 'LO 8/2014', 'La Ley Organica 8/2014 regula el regimen disciplinario de las Fuerzas Armadas.', 2),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'La Unidad Militar de Emergencias (UME) se integra en:', '["Proteccion Civil autonoma","Fuerzas Armadas","Guardia Civil","Sistema Nacional de Salud"]', 'Fuerzas Armadas', 'La UME es una unidad militar especializada en intervencion ante emergencias.', 1),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'Las operaciones en el exterior suelen enmarcarse en compromisos con:', '["ONU, OTAN o UE, entre otros marcos internacionales","Solo acuerdos municipales","Exclusivamente decision privada","Ningun marco internacional"]', 'ONU, OTAN o UE, entre otros marcos internacionales', 'La participacion exterior se articula en marcos juridicos e institucionales internacionales.', 2),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'La disciplina militar se considera:', '["Un valor esencial para la eficacia operativa","Un elemento opcional","Unicamente una formalidad administrativa","Incompatible con derechos fundamentales"]', 'Un valor esencial para la eficacia operativa', 'La disciplina es un pilar de cohesion, mando y eficacia en el ambito militar.', 2),
        ('Fuerzas Armadas', 'Fuerzas Armadas: Estructura y Misiones', 'La cadena de mando en operaciones militares debe caracterizarse por:', '["Ambiguedad funcional","Claridad y jerarquia","Horizontalidad sin responsables","Ausencia de procedimientos"]', 'Claridad y jerarquia', 'La operatividad militar requiere estructura jerarquica y responsabilidades definidas.', 1),

        -- Tecnico Auxiliar Sanitario
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'El derecho a la proteccion de la salud se reconoce en la CE en el articulo:', '["41","42","43","44"]', '43', 'El articulo 43 CE reconoce el derecho a la proteccion de la salud.', 1),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'La Ley General de Sanidad en Espana es la:', '["Ley 14/1986","Ley 41/2002","Ley 16/2003","Ley 33/2011"]', 'Ley 14/1986', 'La Ley 14/1986 configura el marco general del sistema sanitario.', 1),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'La autonomia del paciente y el consentimiento informado se regulan de forma basica en:', '["Ley 39/2015","Ley 41/2002","LO 3/2018","Ley 31/1995"]', 'Ley 41/2002', 'La Ley 41/2002 regula derechos de informacion y autonomia del paciente.', 2),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'La confidencialidad de la informacion clinica exige:', '["Compartir datos con cualquier familiar","Acceso solo por personal autorizado y para finalidad asistencial","Publicar datos anonimizados sin control","Comunicar historiales por mensajeria sin medidas"]', 'Acceso solo por personal autorizado y para finalidad asistencial', 'La informacion sanitaria es especialmente protegida y su acceso debe estar legitimado.', 2),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'La higiene de manos en el entorno asistencial es una medida clave para:', '["Aumentar tiempos de espera","Prevenir infecciones relacionadas con la asistencia","Sustituir toda limpieza ambiental","Evitar registro en historia clinica"]', 'Prevenir infecciones relacionadas con la asistencia', 'Es una medida esencial de seguridad del paciente y control de infecciones.', 1),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'La toma y registro de constantes vitales debe realizarse con:', '["Criterio no estandarizado","Tecnica correcta y registro trazable","Memoria verbal del turno","Solo cuando lo pida el paciente"]', 'Tecnica correcta y registro trazable', 'La trazabilidad del dato clinico mejora continuidad asistencial y seguridad.', 2),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'En movilizacion de pacientes, la prioridad preventiva para el profesional es:', '["Evitar usar ayudas tecnicas","Aplicar ergonomia y tecnicas seguras","Mover sin apoyo para ganar tiempo","Delegar siempre en familiares"]', 'Aplicar ergonomia y tecnicas seguras', 'La movilizacion segura protege al paciente y reduce lesiones musculoesqueleticas del personal.', 2),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'La segregacion de residuos sanitarios debe hacerse:', '["Al final de la semana","En el punto de generacion y segun protocolo","Sin clasificacion previa","Solo en grandes hospitales"]', 'En el punto de generacion y segun protocolo', 'La gestion segura de residuos exige clasificacion y contenedores adecuados desde origen.', 2),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'El trabajo en equipo en unidades asistenciales requiere:', '["Comunicacion efectiva y registro de incidencias","Evitar traspasos de informacion","Actuacion aislada por categoria","Sustituir protocolos por criterio individual"]', 'Comunicacion efectiva y registro de incidencias', 'La continuidad asistencial depende de una comunicacion clara entre profesionales.', 1),
        ('Técnico Auxiliar Sanitario', 'Tecnico Auxiliar Sanitario: Funciones Basicas', 'Ante un cambio clinico relevante del paciente, el tecnico auxiliar debe:', '["Esperar al siguiente turno","Comunicar de inmediato al personal responsable segun protocolo","Modificar tratamiento por iniciativa propia","Dar el alta de forma preventiva"]', 'Comunicar de inmediato al personal responsable segun protocolo', 'La deteccion precoz y la comunicacion oportuna son claves en seguridad del paciente.', 2)
)
INSERT INTO preguntas (tema_id, enunciado, tipo, opciones, respuesta_correcta, explicacion, dificultad)
SELECT t.id, pe.enunciado, 'MCQ', pe.opciones::jsonb, pe.respuesta_correcta, pe.explicacion, pe.dificultad
FROM preguntas_especificas pe
JOIN ramas_oposiciones r ON r.nombre = pe.rama_nombre
JOIN temas t ON t.rama_id = r.id AND t.nombre = pe.tema_nombre;
